server:
  port: 8700

spring:
  application:
    name: springcloud-feign-hystrix
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,health,info,refresh   #配置健康检查包括的视图

eureka:
  client:
    healthcheck:
      enabled: true     #允许健康检查
    serviceUrl:
      defaultZone: http://root:root@localhost:8765/eureka   #注册到eureka服务端的地址
  instance:
    prefer-ip-address: true      #允许使用ip访问，默认使用主机名访问
    #自定义注册到eureka的服务实例名字：应用名：ip：实例端口号
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5 #心跳时间间隔，单位：秒，默认30秒
    lease-expiration-duration-in-seconds: 20  #心跳到期时间，单位秒，默认90秒
    metadata-map:
      zone: ABC      # eureka可以理解的元数据
      king: BBC  # 不会影响客户端行为

#feign默认禁用断路器，需要手动打开，如不需要使用hystrix，可以保持默认配置
feign:
  hystrix:
    enabled: true
