spring:
  application:
    name: eureka-server-cloud-ins1
  security:
    user:
      name: root    #设置用户名为root
      password: root    #设置密码为root
server:
  port: 8761

eureka:
  instance:
    hostname: peer1     #eureka-server实例名称
  client:
    register-with-eureka: false   #是否强制和别的eureka注册中心整合，一般设置成false
    fetch-registry: false    #是否强制和别的eureka注册中心整合，一般设置成false
    serviceUrl:
      defaultZone: http://root:root@localhost:8762/eureka/,http://root:root@localhost:8763/eureka/    #与其他eureka-server实例互相注册
  dashboard:
    enabled:  true #是否允许访问eureka的首页，默认是true
    path: /   #配置访问eureka首页的路径，默认是/
  environment: dev   #eureka首页左上角的environment字样
  datacenter: microservice  #eureka首页左上角的datacenter字样
