
#另外一种写法：对springcloud-feign-comsumer服务的反向代理
#url使用/feign-comsumer/**替代，例如:http://localhost:8099/provider-one/handle
zuul:
  routes:
    abc:  #这里随便写
      path: /feign-comsumer/**
      serviceId: springcloud-feign-comsumer
