
zuul:
  ignoredServices: springcloud-feign-comsumer  #忽略springcloud-feign-comsumer服务的反向代理，'*'为忽略所有，已配置的除外
  routes:
    springcloud-feign-comsumer: /feign-comsumer/**  #对springcloud-feign-comsumer服务的反向代理
    #url使用/feign-comsumer/**替代，例如:http://localhost:8099/feign-comsumer/handle